import type { Component } from 'vue';
import {
  Flame, Heart, Star, Dumbbell, BookOpen, PersonStanding,
  Apple, Droplets, Brain, Bike, Music, Code2, Banknote, Moon, Paintbrush,
  Hammer, Wrench, Trophy, Crown,
  Check, ChevronRight, ChevronDown, ChevronUp, Plus, X,
  LogOut, User, BarChart3, ListChecks, LayoutDashboard,
  Pencil, GripVertical, Trash2, Eye, EyeOff, Filter,
  AlertTriangle, Info, Calendar, CalendarCheck, Bell, Settings,
  HelpCircle, ArrowUpAZ,
} from 'lucide-vue-next';

export const iconMap: Record<string, Component> = {
  'mdi-fire': Flame,
  'mdi-heart': Heart,
  'mdi-star': Star,
  'mdi-dumbbell': Dumbbell,
  'mdi-book-open-variant': BookOpen,
  'mdi-run': PersonStanding,
  'mdi-food-apple': Apple,
  'mdi-cup-water': Droplets,
  'mdi-meditation': Brain,
  'mdi-bike': Bike,
  'mdi-music': Music,
  'mdi-code-braces': Code2,
  'mdi-cash': Banknote,
  'mdi-sleep': Moon,
  'mdi-brush': Paintbrush,
  'mdi-hammer': Hammer,
  'mdi-tools': Wrench,
  'mdi-trophy': Trophy,
  'mdi-crown': Crown,
  'mdi-check': Check,
  'mdi-chevron-right': ChevronRight,
  'mdi-chevron-down': ChevronDown,
  'mdi-chevron-up': ChevronUp,
  'mdi-plus': Plus,
  'mdi-close': X,
  'mdi-logout': LogOut,
  'mdi-account': User,
  'mdi-chart-bar': BarChart3,
  'mdi-format-list-checks': ListChecks,
  'mdi-view-dashboard': LayoutDashboard,
  'mdi-pencil': Pencil,
  'mdi-drag': GripVertical,
  'mdi-delete': Trash2,
  'mdi-eye': Eye,
  'mdi-eye-off': EyeOff,
  'mdi-filter': Filter,
  'mdi-alert': AlertTriangle,
  'mdi-information': Info,
  'mdi-calendar': Calendar,
  'mdi-calendar-check': CalendarCheck,
  'mdi-bell': Bell,
  'mdi-cog': Settings,
  'mdi-sort-ascending': ArrowUpAZ,
};

export function getIcon(mdiString: string): Component {
  return iconMap[mdiString] ?? HelpCircle;
}
